-- MySQL Script generated by MySQL Workbench
-- Wed Oct 10 15:00:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema descifratek_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema descifratek_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `descifratek_db` DEFAULT CHARACTER SET utf8 ;
USE `descifratek_db` ;

-- -----------------------------------------------------
-- Table `descifratek_db`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`actividades` (
  `idActividad` INT(11) NOT NULL,
  `nombreActividad` VARCHAR(25) NOT NULL,
  `fechaActividad` DATE NOT NULL,
  `horaActividad` TIME NOT NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `descifratek_db`.`profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`profesores` (
  `idProfesor` INT(11) NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `apellido` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `idHuella` INT(11) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `descifratek_db`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`cursos` (
  `idCurso` INT(11) NOT NULL,
  `idProfesor` INT(11) NOT NULL,
  `nombreCurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `idProfesor_idx` (`idProfesor` ASC),
  CONSTRAINT `idProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `descifratek_db`.`profesores` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `descifratek_db`.`actividades_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`actividades_cursos` (
  `idActividadCurso` INT(11) NOT NULL,
  `idActividad` INT(11) NOT NULL,
  `idCurso` INT(11) NOT NULL,
  PRIMARY KEY (`idActividadCurso`),
  INDEX `idActividad_idx` (`idActividad` ASC),
  INDEX `idCurso_idx` (`idCurso` ASC),
  CONSTRAINT `idActividad`
    FOREIGN KEY (`idActividad`)
    REFERENCES `descifratek_db`.`actividades` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `descifratek_db`.`cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `descifratek_db`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`administradores` (
  `idAdministrador` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `idHuella` INT(11) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `descifratek_db`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`estudiantes` (
  `idEstudiante` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `idHuella` INT(11) NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `descifratek_db`.`estudiantes_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descifratek_db`.`estudiantes_cursos` (
  `idEstudianteCurso` INT(11) NOT NULL,
  `idEstudiante` INT(11) NOT NULL,
  `idCurso` INT(11) NOT NULL,
  PRIMARY KEY (`idEstudianteCurso`),
  INDEX `idEstudiante_idx` (`idEstudiante` ASC),
  INDEX `idCurso_idx` (`idCurso` ASC),
  CONSTRAINT `idEstudiante`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `descifratek_db`.`estudiantes` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `descifratek_db`.`cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
